path: ""
fileQM9: 'qm9_compl.pkl'
test_ref: "Fold5_Round10_Sample100_mbtr23"

Fold5_Round10_Sample100_mbtr23:
  num_folds: 5
  num_rounds: 10
  column_y: 'U0'
  qtd_sample_qm9: 100
  model:
      per: mol
      regression:
        krr:
          centering: false
          kernel:
            kernel_global:
              kernelf:
                gaussian:
                  ls: 16.0
          nl: 9.5367431640625e-07
      representation:
        composed:
          reps: [{mbtr_2: {acc: 0.001, aindexf: full, broadening: 0.125, eindexf: full,
                  elems: [1, 6, 7, 8, 9], flatten: true, geomf: 1/dot, norm: {none: {}},
                  num: 100, start: -0.05, stop: 1.14, weightf: identity^2}}, 
                 {mbtr_3: {acc: 0.001, aindexf: full, broadening: 0.04419417382415922, eindexf: full,
                  elems: [1, 6, 7, 8, 9], flatten: true, geomf: cos_angle, norm: {simple: {
                  scale: 1.0}}, num: 100, start: -1.05, stop: 1.05, weightf: {exp_-1/norm+norm+norm: {
                  ls: 524288.0}}}}]


