path: ""
fileQM9: 'qm9_compl.pkl'
test_ref: "Fold5_Round10_Sample10000_sf23"

Fold5_Round10_Sample10000_sf23:
  num_folds: 5
  num_rounds: 10
  column_y: 'U0'
  qtd_sample_qm9: 10000
  model:
      per: mol
      regression:
        krr:
          centering: false
          kernel:
            kernel_atomic:
              kernelf:
                gaussian:
                  ls: 2.8284271247461903
              norm: false
          nl: 8.631674575031098e-05
      representation:
        composed:
          reps: [{sf:
                    {dim: null,
                     elemental: [],
                     elems: [1, 6, 7, 8, 9],
                     universal: [{rad_shifted: {cutoff: 3, n: 5}},
                                 {rad_centered: {cutoff: 2, n: 2}},
                                 {ang: {cutoff: 3, eta: 0.1767766952966369, lambd: 1, zeta: 1}}, 
                                 {ang: {cutoff: 5, eta: 0.0625, lambd: -1, zeta: 1}}, 
                                 {ang: {cutoff: 3, eta: 0.08838834764831845, lambd: 1, zeta: 2}}, 
                                 {ang: {cutoff: 5, eta: 0.005524271728019903, lambd: -1, zeta: 2}}, 
                                 null, 
                                 {ang: {cutoff: 6, eta: 0.011048543456039806, lambd: -1, zeta: 4}} 
                                ]
                    }
                  }
                 ]



      
