path: ""
fileQM9: 'qm9_compl.pkl'
test_ref: "Fold5_Round10_Sample100_sf2"

Fold5_Round10_Sample100_sf2:
  num_folds: 5
  num_rounds: 10
  column_y: 'U0'
  qtd_sample_qm9: 100
  model:
      per: mol
      regression:
        krr:
          centering: false
          kernel:
            kernel_atomic:
              kernelf:
                gaussian:
                  ls: 32.0
              norm: false
          nl: 0.0001220703125
      representation:
        composed:
          reps: [{sf:
                    {dim: null,
                     elemental: [],
                     elems: [1, 6, 7, 8, 9],
                     universal: [{  rad_shifted: {cutoff: 3, n: 9}  },
                                 {  rad_centered: {cutoff: 4, n: 8}  }
                                ]
                    }
                  }
                 ]



      
