path: ""
fileQM9: 'qm9_compl.pkl'
test_ref: "Fold5_Round10_Sample10000_soap"

Fold5_Round10_Sample10000_soap:
  num_folds: 5
  num_rounds: 10
  column_y: 'U0'
  qtd_sample_qm9: 10000
  model:
      per: mol
      regression:
        krr:
          centering: false
          kernel:
            kernel_atomic:
              kernelf:
                gaussian:
                  ls: 2.0
              norm: false
          nl: 9.5367431640625e-07
      representation:
        composed:
          reps: [{ds_soap: {
                  cutoff: 2,
                  elems: [1, 6, 7, 8, 9],
                  l_max: 5,
                  n_max: 8,
                  rbf: gto,
                  sigma: 0.25}
                 }   
                 ]




      
